"""
Notifier - sends acknowledgement notifications (email + WhatsApp) summarising
what each MCC pipeline discovered/uploaded in this run.
"""
from __future__ import annotations

import logging
import os
import smtplib
import ssl
import urllib.parse
import urllib.request
from datetime import datetime
from email.message import EmailMessage
from html import escape


def _change_count(summary: dict) -> int:
    if summary.get("pipeline") == "main_mcc":
        return int(summary.get("new", 0)) + int(summary.get("updated", 0))
    if summary.get("pipeline", "").startswith("admissions"):
        return len(summary.get("new_institutes") or [])
    return 0


def total_changes(summaries):
    return sum(_change_count(s or {}) for s in summaries)


_HTML_HEAD = '<!doctype html><html><body style="font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #222; line-height: 1.45; max-width: 720px; margin: 0 auto;">'
_HTML_FOOT = '<p style="color:#888; font-size:12px; margin-top:32px;">This message was generated by your MCC mirror pipeline. You can stop receiving these by setting <code>notify.enabled: false</code> in <code>config.yaml</code>.</p></body></html>'


def _section_main(summary):
    if not summary:
        return ""
    new_files = summary.get("new_files") or []
    counts = "new={} | updated={} | skipped={} | failed={}".format(
        summary.get("new", 0), summary.get("updated", 0),
        summary.get("skipped", 0), summary.get("failed", 0),
    )
    body = [
        '<h2 style="background:#1a73e8;color:#fff;padding:8px 12px;border-radius:4px;font-size:16px;">Main MCC website (mcc.nic.in)</h2>',
        '<p><strong>Counts:</strong> ' + escape(counts) + '</p>',
    ]
    if new_files:
        body.append("<p><strong>New PDFs added (top 50 shown):</strong></p>")
        body.append("<ul>")
        for f in new_files[:50]:
            link = f.get("drive_link") or "#"
            title = escape(f.get("title") or f.get("filename") or "")
            path = escape(f.get("drive_path") or "")
            body.append('<li><a href="' + escape(link) + '">' + title + '</a> <span style="color:#888;font-size:12px;">- ' + path + '</span></li>')
        body.append("</ul>")
        if len(new_files) > 50:
            body.append('<p style="color:#888;font-size:13px;">... plus ' + str(len(new_files) - 50) + ' more new PDFs.</p>')
    else:
        body.append('<p style="color:#888;">No new PDFs added in this run.</p>')
    return "\n".join(body)


def _section_admissions(summary):
    if not summary:
        return ""
    course = summary.get("course") or ""
    new_inst = summary.get("new_institutes") or []
    title = "Institute Profiles - " + escape(course) + " (" + ("NEET PG" if course == "PG" else "NEET UG") + " Counselling 2025)"
    body = [
        '<h2 style="background:#137333;color:#fff;padding:8px 12px;border-radius:4px;font-size:16px;">' + title + '</h2>',
        "<p><strong>Total institutes processed:</strong> " + str(summary.get("institutes", 0)) + " | <strong>profile PDFs uploaded:</strong> " + str(summary.get("profile_uploaded", 0)) + " | <strong>bond PDFs uploaded:</strong> " + str(summary.get("bond_uploaded", 0)) + "</p>",
    ]
    if new_inst:
        body.append('<p><strong>New institutes since last run (' + str(len(new_inst)) + '):</strong></p>')
        body.append("<ul>")
        for inst in new_inst[:50]:
            code = escape(inst.get("code", ""))
            name = escape(inst.get("name", ""))
            plink = inst.get("profile_link") or ""
            blink = inst.get("bond_link") or ""
            cells = ['<strong>' + code + '</strong> - ' + name]
            if plink:
                cells.append(' <a href="' + escape(plink) + '">[Profile]</a>')
            if blink:
                cells.append(' <a href="' + escape(blink) + '">[Bond]</a>')
            body.append("<li>" + "".join(cells) + "</li>")
        body.append("</ul>")
        if len(new_inst) > 50:
            body.append('<p style="color:#888;font-size:13px;">... plus ' + str(len(new_inst) - 50) + ' more new institutes.</p>')
    else:
        body.append('<p style="color:#888;">No new institutes since last run.</p>')
    return "\n".join(body)


def build_email(summaries):
    today = datetime.now().strftime("%Y-%m-%d")
    total = total_changes(summaries)
    if total == 0:
        subject = "MCC mirror - no changes (" + today + ")"
    else:
        subject = "MCC mirror - " + str(total) + " update(s) (" + today + ")"
    sections = []
    for s in summaries or []:
        kind = (s or {}).get("pipeline", "")
        if kind == "main_mcc":
            sections.append(_section_main(s))
        elif kind.startswith("admissions"):
            sections.append(_section_admissions(s))
    intro = "<p>Hi,</p><p>Your MCC mirror just finished a run on <strong>" + escape(today) + "</strong>. Total changes detected across all sources: <strong>" + str(total) + "</strong>.</p>"
    drive_root = '<p style="margin-top:24px;"><a href="https://drive.google.com/drive/folders/1GHoHguP6DZGXBtcTRDWHNbbd-zACsDYY">Open the MCC Archive folder in Google Drive</a></p>'
    html = _HTML_HEAD + intro + "\n".join(sections) + drive_root + _HTML_FOOT
    return subject, html


def _send_email_smtp(cfg_notify, subject, html_body, log):
    smtp_cfg = cfg_notify.get("smtp", {})
    host = smtp_cfg.get("host", "smtp.gmail.com")
    port = int(smtp_cfg.get("port", 587))
    sender = smtp_cfg.get("sender", "")
    app_password = (os.environ.get("GMAIL_APP_PASSWORD", "").strip()
                    or smtp_cfg.get("app_password", "").strip())
    to_addr = (os.environ.get("NOTIFY_EMAIL_TO", "").strip()
               or cfg_notify.get("to", ""))
    if not (sender and app_password and to_addr):
        log.warning("notify: missing sender/app_password/to - skipping send")
        return False
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_addr
    msg.set_content("Plain-text fallback. Open HTML version.")
    msg.add_alternative(html_body, subtype="html")
    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.ehlo()
            server.login(sender, app_password)
            server.send_message(msg)
        log.info("notify: email sent to " + to_addr + " (subject: " + subject + ")")
        return True
    except Exception as e:
        log.exception("notify: SMTP send failed: " + str(e))
        return False


def _build_whatsapp_text(summaries):
    today = datetime.now().strftime("%Y-%m-%d")
    total = total_changes(summaries)
    lines = []
    lines.append("*MCC mirror - " + str(total) + " update(s)* (" + today + ")")
    lines.append("")
    for s in summaries or []:
        kind = (s or {}).get("pipeline", "")
        if kind == "main_mcc":
            new_files = s.get("new_files") or []
            lines.append("*Main MCC site:* new=" + str(s.get("new", 0)) + ", updated=" + str(s.get("updated", 0)) + ", failed=" + str(s.get("failed", 0)))
            for f in new_files[:5]:
                title = (f.get("title") or f.get("filename") or "")[:60]
                lines.append("  - " + title)
            if len(new_files) > 5:
                lines.append("  ...and " + str(len(new_files) - 5) + " more")
        elif kind.startswith("admissions"):
            course = s.get("course", "")
            new_inst = s.get("new_institutes") or []
            lines.append("*Profiles " + course + ":* total=" + str(s.get("institutes", 0)) + ", new institutes=" + str(len(new_inst)))
            for inst in new_inst[:5]:
                code = inst.get("code", "")
                name = (inst.get("name") or "")[:50]
                lines.append("  - " + code + " - " + name)
            if len(new_inst) > 5:
                lines.append("  ...and " + str(len(new_inst) - 5) + " more")
        lines.append("")
    lines.append("Drive: https://drive.google.com/drive/folders/1GHoHguP6DZGXBtcTRDWHNbbd-zACsDYY")
    return "\n".join(lines)


def _send_whatsapp_callmebot(cfg_whatsapp, text, log):
    phone = (os.environ.get("WHATSAPP_PHONE", "").strip()
             or str(cfg_whatsapp.get("phone", "")).strip())
    api_key = (os.environ.get("WHATSAPP_API_KEY", "").strip()
               or str(cfg_whatsapp.get("api_key", "")).strip())
    if not phone or not api_key:
        log.warning("notify: WhatsApp phone or api_key missing - skipping send")
        return False
    if not phone.startswith("+"):
        log.info("notify: prefixing '+' to WhatsApp phone " + phone[:4] + "***")
        phone = "+" + phone
    if len(text) > 1800:
        text = text[:1780] + "\n\n[truncated]"
    url = ("https://api.callmebot.com/whatsapp.php"
           + "?phone=" + urllib.parse.quote(phone)
           + "&text=" + urllib.parse.quote(text)
           + "&apikey=" + urllib.parse.quote(api_key))
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            body = resp.read().decode("utf-8", errors="replace")[:300]
        log.info("notify: WhatsApp send response (200): " + body[:120])
        return True
    except Exception as e:
        log.exception("notify: WhatsApp send failed: " + str(e))
        return False


def send_run_notification(cfg, summaries, log):
    cfg_notify = (cfg or {}).get("notify", {}) or {}
    if not cfg_notify.get("enabled", False):
        log.info("notify: disabled in config - skipping")
        return False
    total = total_changes(summaries)
    if total == 0 and cfg_notify.get("skip_if_no_changes", True):
        log.info("notify: no changes this run - skipping notifications per config")
        return False
    sent_anything = False
    try:
        subject, html = build_email(summaries)
        if _send_email_smtp(cfg_notify, subject, html, log):
            sent_anything = True
    except Exception as e:
        log.exception("notify: email send threw: " + str(e))
    cfg_whatsapp = cfg_notify.get("whatsapp", {}) or {}
    if cfg_whatsapp.get("enabled", False):
        try:
            text = _build_whatsapp_text(summaries)
            if _send_whatsapp_callmebot(cfg_whatsapp, text, log):
                sent_anything = True
        except Exception as e:
            log.exception("notify: whatsapp send threw: " + str(e))
    else:
        log.info("notify: whatsapp disabled in config - skipping")
    return sent_anything
