"""
Notifier — sends a single Gmail email summarising what each MCC pipeline
discovered/uploaded in this run. Designed to be called once per
orchestrator cycle, with summaries from all three pipelines passed in.

Usage:
    from notifier import send_run_notification
    send_run_notification(
        cfg=cfg,
        summaries=[main_summary, pg_summary, ug_summary],
        log=log,
    )

Configuration (in config.yaml):
    notify:
      enabled: true
      to: teamtabindia@gmail.com
      smtp:
        host: smtp.gmail.com
        port: 587
        sender: teamtabindia@gmail.com
        app_password: "xxxx xxxx xxxx xxxx"   # 16-char Gmail App Password
      skip_if_no_changes: true
"""
from __future__ import annotations

import logging
import os
import smtplib
import ssl
from datetime import datetime
from email.message import EmailMessage
from html import escape


# ---------------------------------------------------------------------------
# Counting + filtering
# ---------------------------------------------------------------------------


def _change_count(summary: dict) -> int:
    """How many 'new' items did this pipeline produce?
    Main MCC -> count of newly-added PDFs.
    Admissions -> count of newly-added institutes.
    """
    if summary.get("pipeline") == "main_mcc":
        return int(summary.get("new", 0)) + int(summary.get("updated", 0))
    if summary.get("pipeline", "").startswith("admissions"):
        return len(summary.get("new_institutes") or [])
    return 0


def total_changes(summaries: list[dict]) -> int:
    return sum(_change_count(s or {}) for s in summaries)


# ---------------------------------------------------------------------------
# Email body builders
# ---------------------------------------------------------------------------


_HTML_HEAD = """\
<!doctype html>
<html><body style="font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    color: #222; line-height: 1.45; max-width: 720px; margin: 0 auto;">
"""

_HTML_FOOT = """\
<p style="color:#888; font-size:12px; margin-top:32px;">
This message was generated by your MCC mirror pipeline.
You can stop receiving these by setting <code>notify.enabled: false</code>
in <code>config.yaml</code>.
</p>
</body></html>
"""


def _section_main(summary: dict) -> str:
    if not summary:
        return ""
    new_files = summary.get("new_files") or []
    counts = (
        f"new={summary.get('new', 0)} | "
        f"updated={summary.get('updated', 0)} | "
        f"skipped={summary.get('skipped', 0)} | "
        f"failed={summary.get('failed', 0)}"
    )
    body = [
        '<h2 style="background:#1a73e8;color:#fff;padding:8px 12px;border-radius:4px;font-size:16px;">'
        'Main MCC website (mcc.nic.in)</h2>',
        f'<p><strong>Counts:</strong> {escape(counts)}</p>',
    ]
    if new_files:
        body.append("<p><strong>New PDFs added (top 50 shown):</strong></p>")
        body.append("<ul>")
        for f in new_files[:50]:
            link = f.get("drive_link") or "#"
            title = escape(f.get("title") or f.get("filename") or "")
            path = escape(f.get("drive_path") or "")
            body.append(
                f'<li><a href="{escape(link)}">{title}</a>'
                f' <span style="color:#888;font-size:12px;">— {path}</span></li>'
            )
        body.append("</ul>")
        if len(new_files) > 50:
            body.append(
                f'<p style="color:#888;font-size:13px;">'
                f'... plus {len(new_files) - 50} more new PDFs.</p>'
            )
    else:
        body.append('<p style="color:#888;">No new PDFs added in this run.</p>')
    return "\n".join(body)


def _section_admissions(summary: dict) -> str:
    if not summary:
        return ""
    course = summary.get("course") or ""
    new_inst = summary.get("new_institutes") or []
    title = (
        f'Institute Profiles — {escape(course)} '
        f'({"NEET PG" if course == "PG" else "NEET UG"} Counselling 2025)'
    )
    body = [
        f'<h2 style="background:#137333;color:#fff;padding:8px 12px;'
        f'border-radius:4px;font-size:16px;">{title}</h2>',
        f"<p><strong>Total institutes processed:</strong> {summary.get('institutes', 0)}"
        f" | <strong>profile PDFs uploaded:</strong> {summary.get('profile_uploaded', 0)}"
        f" | <strong>bond PDFs uploaded:</strong> {summary.get('bond_uploaded', 0)}</p>",
    ]
    if new_inst:
        body.append(f'<p><strong>New institutes since last run ({len(new_inst)}):</strong></p>')
        body.append("<ul>")
        for inst in new_inst[:50]:
            code = escape(inst.get("code", ""))
            name = escape(inst.get("name", ""))
            plink = inst.get("profile_link") or ""
            blink = inst.get("bond_link") or ""
            cells = [f'<strong>{code}</strong> — {name}']
            if plink:
                cells.append(f' <a href="{escape(plink)}">[Profile]</a>')
            if blink:
                cells.append(f' <a href="{escape(blink)}">[Bond]</a>')
            body.append(f"<li>{''.join(cells)}</li>")
        body.append("</ul>")
        if len(new_inst) > 50:
            body.append(
                f'<p style="color:#888;font-size:13px;">'
                f'... plus {len(new_inst) - 50} more new institutes.</p>'
            )
    else:
        body.append('<p style="color:#888;">No new institutes since last run.</p>')
    return "\n".join(body)


def build_email(summaries: list[dict]) -> tuple[str, str]:
    """Returns (subject, html_body) for the run summary."""
    today = datetime.now().strftime("%Y-%m-%d")
    total = total_changes(summaries)

    if total == 0:
        subject = f"MCC mirror — no changes ({today})"
    else:
        subject = f"MCC mirror — {total} update(s) ({today})"

    sections = []
    for s in summaries or []:
        kind = (s or {}).get("pipeline", "")
        if kind == "main_mcc":
            sections.append(_section_main(s))
        elif kind.startswith("admissions"):
            sections.append(_section_admissions(s))

    intro = (
        f'<p>Hi,</p>'
        f'<p>Your MCC mirror just finished a run on <strong>{escape(today)}</strong>. '
        f'Total changes detected across all sources: <strong>{total}</strong>.</p>'
    )
    drive_root = (
        '<p style="margin-top:24px;">'
        '<a href="https://drive.google.com/drive/folders/1GHoHguP6DZGXBtcTRDWHNbbd-zACsDYY">'
        'Open the MCC Archive folder in Google Drive →</a></p>'
    )
    html = _HTML_HEAD + intro + "\n".join(sections) + drive_root + _HTML_FOOT
    return subject, html


# ---------------------------------------------------------------------------
# SMTP send
# ---------------------------------------------------------------------------


def _send_email_smtp(cfg_notify: dict, subject: str, html_body: str,
                     log: logging.Logger) -> bool:
    smtp_cfg = cfg_notify.get("smtp", {})
    host = smtp_cfg.get("host", "smtp.gmail.com")
    port = int(smtp_cfg.get("port", 587))
    sender = smtp_cfg.get("sender", "")
    # Prefer env var (so we don't need plaintext app password in config.yaml).
    # Falls back to config value for backwards compat / local convenience.
    app_password = (os.environ.get("GMAIL_APP_PASSWORD", "").strip()
                    or smtp_cfg.get("app_password", "").strip())
    to_addr = (os.environ.get("NOTIFY_EMAIL_TO", "").strip()
               or cfg_notify.get("to", ""))

    if not (sender and app_password and to_addr):
        log.warning("notify: missing sender/app_password/to — skipping send")
        return False

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_addr
    msg.set_content(
        "This message uses HTML formatting. "
        "If you're seeing this, your client is plain-text only — "
        "please open the HTML version or visit the Drive folder."
    )
    msg.add_alternative(html_body, subtype="html")

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.ehlo()
            server.login(sender, app_password)
            server.send_message(msg)
        log.info(f"notify: email sent to {to_addr} (subject: {subject})")
        return True
    except Exception as e:
        log.exception(f"notify: SMTP send failed: {e}")
        return False


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def send_run_notification(cfg: dict, summaries: list[dict],
                          log: logging.Logger) -> bool:
    cfg_notify = (cfg or {}).get("notify", {}) or {}
    if not cfg_notify.get("enabled", False):
        log.info("notify: disabled in config — skipping")
        return False

    total = total_changes(summaries)
    if total == 0 and cfg_notify.get("skip_if_no_changes", True):
        log.info("notify: no changes this run — skipping email per config")
        return False

    subject, html = build_email(summaries)
    return _send_email_smtp(cfg_notify, subject, html, log)
